### ISSUE TITLE
Discussion on discord for color.

### ISSUE THREAD

**Issue by Ru4vader** [Lopezkneiv/Moffat-Bay#32]

**Comment by Lopezkneiv** [comment]
https://www.lodgeatgiantsridge.com/?gad_source=1&gclid=CjwKCAjwz42xBhB9EiwA48pT73zrFwz4rJBCTZPE7vwnUdblLRUxYdMTd87yeNcPNqK6EVTacllklhoCbccQAvD_BwE

https://www.craguns.com/offers?gad_source=1&gclid=CjwKCAjwz42xBhB9EiwA48pT7xh8nRpNqaNbB5sgZTzg1geZS8SpslQ3tl_UlN3UW-ZuW8foTTmXYxoCgGoQAvD_BwE&gclsrc=aw.ds

https://www.bluefinbay.com/?gad_source=1&gclid=CjwKCAjwz42xBhB9EiwA48pT7w0B514dudd7nzmYIT-CaN4kugaRGnQImCujDUlREzJtciSMOOPYKRoCq50QAvD_BwE

https://getaway.house/wild-rose/?utm_source=google&utm_medium=cpc&utm_term=cabin&utm_campaign=NB_Dynamic_ATL&gad_source=1&gclid=CjwKCAjwz42xBhB9EiwA48pT76bEgUxwMAeSrZbpz_M_dP50zGpmM4iOT74PLJfpc7v9fI58ftTGUhoCFJYQAvD_BwE

https://www.venetianwaterpark.com//

**Comment by kolsen** [comment]
Item is complete closing issue.
